version: '2.2'
services:
  postgres-db:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ 'CMD', 'pg_isready', "-q", "-d", "postgres", "-U", "postgres" ]
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 5s

  # this second PostgresSQL is used when running test
  postgres-db-test:
    image: postgres:latest
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: shopping-cart
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

